### ISSUE TITLE
Error: mkdir: cannot create directory '/run/php': File exists 

### ISSUE THREAD

**Issue by seth-space** [jokob-sk/Pi.Alert#132]
**Describe the issue**
Error: mkdir: cannot create directory '/run/php': File exists 
pialert starts for a few seconds and restarts in a loop.

**Paste last few lines from `pialert.log`**

```Error in Docker log:
Starting nginx:nginx
mkdir: cannot create directory '/run/php': File exists```


``

**Paste your `pialert.conf` (remove personal info)**

#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# GENERAL settings
# ----------------------

PRINT_LOG               = False
TIMEZONE                = 'Europe/Amsterdam'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

# EMAIL settings
# ----------------------
SMTP_SERVER             = 'smtp.gmail.com'
SMTP_PORT               = 587
SMTP_USER               = 'user@gmail.com'
SMTP_PASS               = 'password'
SMTP_SKIP_TLS           = False
SMTP_SKIP_LOGIN	        = False

REPORT_MAIL             = False
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = 'user@gmail.com'
REPORT_DEVICE_URL       = 'http://pi.alert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'http://pi.alert/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD         = 'json'       # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD  = 'GET'        # POST, GET...

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_HOST               = 'https://ntfy.sh'
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'
NTFY_USER               = 'user'       # set username... 
NTFY_PASSWORD           = 'passw0rd'   # ...and password if authentication is used https://docs.ntfy.sh/config/#users-and-roles

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# MQTT settings
# ----------------------
REPORT_MQTT             = False
MQTT_BROKER             = '192.168.1.2'
MQTT_PORT               = 1883
MQTT_USER               = 'mqtt'
MQTT_PASSWORD           = 'passw0rd'
MQTT_QOS                = 0
MQTT_DELAY_SEC          = 2            # delay in seconds, increase if not all devices are created in Home Assistant

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False                         # if enabled you need to map '/etc/pihole/pihole-FTL.db' in docker-compose.yml
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False                         # if enabled you need to map '/etc/pihole/dhcp.leases' in docker-compose.yml
#DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'
#
# Scan multiple interfaces (eth1 and eth0):
SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

SCAN_SUBNETS            = '--localnet'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
Installed pi alert via docker compose on Synology DSM 7.0
used yaml:

version: "3"
services:
pialert:
container_name: pialert
image: "jokobsk/pi.alert:latest"
network_mode: "host"
restart: unless-stopped
volumes:

/volume1/docker/pialert/config:/home/pialert/config
/volume1/docker/pialert/db/pialert.db:/home/pialert/db/pialert.db
/volume1/containers/pialert/db/setting_darkmode:/home/pi/pialert/db/setting_darkmode
environment:
TZ=Europe/Amsterdam
HOST_USER_ID=1000
HOST_USER_GID=1000
PORT=20211
SSH output:
Ed@Syno1522:/volume1/docker/pialert$ docker-compose up

Removing pialert

Starting 599d4351fbe6_pialert ... done

Attaching to 599d4351fbe6_pialert

599d4351fbe6_pialert | mkdir: cannot create directory '/run/php': File exists

599d4351fbe6_pialert | Starting nginx: nginx.

599d4351fbe6_pialert exited with code 1

paste here

```


`.env` 
```

paste here

```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by jokob-sk** [comment]
Hi there,

The above error isn't causing any problems and is only an installation artefact. 

Please try to remove this line from the config:

`SCAN_SUBNETS            = '--localnet'`

Make sure the interfaces and ip masks listed in this setting are correct:
`SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]`


Make sure these environment variables are correct (run `sudo awk -F: '($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd `  on the server to doublecheck):

`HOST_USER_ID=1000`

Make also sure your DB and config have correct permissions.

Thanks

**Comment by seth-space** [comment]
Removed localnet
used:
Ed@Syno1522:/volume1/docker/pialert$ id
uid=1026(Ed) gid=100(users) groups=100(users),101(administrators),65536(docker)

and adapted the yml file with:
environment:
      - TZ=Europe/Amsterdam
      - HOST_USER_ID=1028  
      - HOST_USER_GID=100
      - PORT=20211
changed the permissions for config, db, log to network user: host_user_id=1028

your command results:

Ed@Syno1522:~$ sudo awk -F: '($3 >= 1000) {printf "%s:%s\n",$1,$3}' /etc/passwd                            ActiveBackup:192868
admin:1024
Antivirus:196791
AudioStation:254178
CloudSync:177120
CodecPack:288235
DhcpServer:105872
DocumentViewer:183237
Ed:1026
FileStation:179652
guest:1025
http:1023
LMS:1027
MediaServer:118831
Network user:1028
OAuthService:226662
office:198276
PlexMediaServer:297536
Python2:236506
sc-filebrowser:173455
sc-python310:241369
sc-sabnzbd:225033
SecureSignIn:136917
StorageAnalyzer:276949
SurveillanceStation:233155
SynoFinder:195341
SynologyApplicationService:130369
SynologyDrive:153742
SynologyPhotos:105733
tailscale:165290
VideoStation:228233
VirtualHere:189563
Virtualization:185921

**Comment by seth-space** [comment]
still no success... keeps restarting.
log gives same senseless info: 
mkdir: cannot create directory '/run/php': File exists

============

conf:
#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# GENERAL settings
# ----------------------

PRINT_LOG               = False
TIMEZONE                = 'Europe/Amsterdam'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

# EMAIL settings
# ----------------------
SMTP_SERVER             = 'smtp.gmail.com'
SMTP_PORT               = 587
SMTP_USER               = 'user@gmail.com'
SMTP_PASS               = 'password'
SMTP_SKIP_TLS           = False
SMTP_SKIP_LOGIN	        = False

REPORT_MAIL             = False
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = 'user@gmail.com'
REPORT_DEVICE_URL       = 'http://pi.alert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'http://pi.alert/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD         = 'json'       # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD  = 'GET'        # POST, GET...

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_HOST               = 'https://ntfy.sh'
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'
NTFY_USER               = 'user'       # set username... 
NTFY_PASSWORD           = 'passw0rd'   # ...and password if authentication is used https://docs.ntfy.sh/config/#users-and-roles

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# MQTT settings
# ----------------------
REPORT_MQTT             = False
MQTT_BROKER             = '192.168.1.2'
MQTT_PORT               = 1883
MQTT_USER               = 'mqtt'
MQTT_PASSWORD           = 'passw0rd'
MQTT_QOS                = 0
MQTT_DELAY_SEC          = 2            # delay in seconds, increase if not all devices are created in Home Assistant

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False                         # if enabled you need to map '/etc/pihole/pihole-FTL.db' in docker-compose.yml
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False                         # if enabled you need to map '/etc/pihole/dhcp.leases' in docker-compose.yml
#DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'
#
# Scan multiple interfaces (eth1 and eth0):
SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

SCAN_SUBNETS            = '--localnet'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90

**Comment by jokob-sk** [comment]
Thanks for that. Hummmm, nothing out of the ordinary.

**Comment by acbgbca** [comment]
The latest build has also broken for me. This is the error from the Docker logs on start:

```
Starting nginx: nginx.
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2516, in <module>
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 212, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2249, in upgradeDB
```

There is nothing in pialert.log

I get the same error whether I change the UID/GID or not, and the owner of the loaded volumes matches the running user.

**Comment by acbgbca** [comment]
@seth-space the previous docker image works fine, you could try using `image: "jokobsk/pi.alert:sha-ccc33bf"` until this is resolved.

**Comment by jokob-sk** [comment]
@acbgbca thanks for reporting, try redownloading the latest image once this  build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/3768882488

I've implemented additional logging, so your issue might be easier to debug

**Comment by acbgbca** [comment]
@jokob-sk here is the log output:

```
Starting nginx: nginx.
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2516, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 212, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2249, in upgradeDB
 File "/home/pi/pialert/back/pialert.py", line 2342, in openDB
    print_log ('Opening DB...')    
  File "/home/pi/pialert/back/pialert.py", line 2409, in print_log
    log_timestamp2 - log_timestamp, ' ',
NameError: name 'log_timestamp' is not defined
```

I don't think it is a permissions error, I think it is a bug in the pialert script

**Comment by jokob-sk** [comment]
Hey, thanks!

Is this the latest image? I pushed a new one today where I think I fixed this.

**Comment by acbgbca** [comment]
@jokob-sk I re-pulled the image to ensure it was the latest. Revision da3ac551225e1881f0eb48a2059386c9d8851b79 according to the labels which matches the PUSHPROD. Still getting the same error:

```
Starting nginx: nginx.

 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2550, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 262, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2287, in upgradeDB
    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2383, in openDB
    print_log ('Opening DB...')   
  File "/home/pi/pialert/back/pialert.py", line 2451, in print_log
    log_timestamp2 - log_timestamp, ' ',
NameError: name 'log_timestamp' is not defined
```

**Comment by jokob-sk** [comment]
@acbgbca thanks a bunch for checking it again. Found [the issue](https://github.com/jokob-sk/Pi.Alert/commit/d6a5f23345c390e3ea9d96034ea83bc1cb1d0d31#r94139993) and building a new image.

Funny thing is that I could have sworn that I fixed it already. Felt a dejavu implementing it again. Anyway, let me know if the issue persists in the [latest build](https://github.com/jokob-sk/Pi.Alert/actions/runs/3773312122). Thanks again for the help!

**Comment by acbgbca** [comment]
@jokob-sk confirmed, all working for me now. Thank you for the quick resolution.

**Comment by jokob-sk** [comment]
@acbgbca thanks for your patience!

**Comment by seth-space** [comment]
used the new image and now i have some errors and pialert is running.
error:
 Starting nginx: nginx.
pialert    | WARNING: Could not obtain IP address for interface eth1. Using 0.0.                     0.0 for
pialert    | the source address, which may not be what you want.
pialert    | Either configure eth1 with an IP address, or manually specify the a                     ddress
pialert    | with the --arpspa option.
pialert    | ERROR: Could not obtain interface IP address and netmask
pialert    | ERROR: pcap_lookupnet: eth1: no IPv4 address assigned

after a few minutes pialert stopped with these errors in the logging.

**Comment by jokob-sk** [comment]
Hi @seth-space !

Please make sure you set the `SCAN_SUBNETS` variable/setting according to instructions if you haven't already done so.

As the error says. make sure you set the  permissions appropriately. It seems like the app doesn't have read permissions to the `pialert.conf` file according to the error below:

> Failed to copy file /home/pi/pialert/config/pialert.conf to /home/pi/pialert/config/pialert.conf_2022-12-29_22-02-22.backup
Check your permissions to allow read/write access to the /config folder.Unable to open file!

You can ssh into the container and execute:

`sudo chmod a+rw -R /home/pi/pialert/config`

This will grant read and write permissions to everyone to the contents of that folder. 

Hope this helps!
j

**Comment by seth-space** [comment]
not sure how to ssh in a container without a ipnumber. So i used the filemanagement of synology to set the "everyone" on the pialert map. ("everyone" remembered some old windows traumas , brrr)
Everything seems to work now.
Thanks..

**Comment by jokob-sk** [comment]
I guess this will depend on your system setup, so I can't comment on how your permissions work (and I'm by no means a security/permissions expert myself :)

Glad it works though and I'll close this for now as the app-specific issue got resolved, Will re-open if needed.
