### ISSUE TITLE
Error Message in logs and not send nodification

### ISSUE THREAD

**Issue by gregtux77** [jokob-sk/Pi.Alert#163]
hello i m an error with latest version, this's same problem ?

sys.exit(main())
File "/home/pi/pialert/back/pialert.py", line 599, in main
send_notifications()
File "/home/pi/pialert/back/pialert.py", line 2281, in send_notifications
update_api(True)
File "/home/pi/pialert/back/pialert.py", line 3100, in update_api
write_file(folder + 'notification_text.txt' , mail_text)
File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
file = open (pPath, 'w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'

moreover I note that the swap is filled progressively...

image :jokobsk/pi.alert:latest
Raspi : P4 

tky for your time

**Comment by masterwishx** [comment]
Also have this problem and stoped app ...

![image](https://user-images.githubusercontent.com/28630321/216627337-35f544a7-16a4-4b65-95fb-f31b79eed446.png)

**Comment by masterwishx** [comment]
Using last version in Unraid (Linux x64) Docker

**Comment by masterwishx** [comment]
@gregtux77 

Fixed by disabled API setting and changed Pi.Alert URL to my http://192.168.0.199:20211

but still dont know why was problem with API in last version ....

maybe becose we need to add  to docker setup :

 ${DEV_LOCATION}/front/api:/home/pi/pialert/front/api 

i dint checked it ....

**Comment by gregtux77** [comment]
hi,
I just did the test by disabling API. I have the same problem, always an error message.
![image](https://user-images.githubusercontent.com/34283203/216648753-c133840f-8d94-4fce-a1e2-c23d1f378652.png)


the "Apprise" component still does not work with a telegram account
![image](https://user-images.githubusercontent.com/34283203/216649743-cbaac3fe-2ecb-4d36-8a56-a7ca73167e8f.png)

**Comment by masterwishx** [comment]
Did you also changed pi.Alert URL from default to you URL?

**Comment by masterwishx** [comment]
I have only webhook for discord for now...

**Comment by gregtux77** [comment]
> Did you also changed pi.Alert URL from default to you URL?

I changed the url for my local domain

**Comment by masterwishx** [comment]
Still have error and stopped container?
Try to update container, maybe need to remove and then recreate...
Or add to docker setup
${DEV_LOCATION}/front/api:/home/pi/pialert/front/api

**Comment by jokob-sk** [comment]
Hi @masterwishx  @gregtux77 !

Thanks for reporting and helping out @masterwishx ! Really appreciate it :)

I think I know what's wrong. I'll confirm in a few hours, but I think:

1) The script is failing on the missing 'home/pi/pialert/front/api' folder so probably the fix is to
2) Disable the API by setting `ENABLE_API=False` in the `pialert.conf` file or in the settings
3) SSH into the container and run `mkdir /home/pi/pialert/front/api`
4) Enabling the API again by setting `ENABLE_API=True`

Cause if interested:

I created the /api/ directory on my local dev environment, but wanted to exclude sensitive data so placed a gitignore file in the folder, which completely removed the whole folder from the source.

**Comment by jokob-sk** [comment]
FYI Confirmed: The above workaround works on my end. Will be fixed in the next release.

**Comment by jokob-sk** [comment]
For those who are impatient, this dev build should fix the issue:

DockerHub image tag is:

`jokobsk/pi.alert_dev:sha-b5f0a64`

**Comment by masterwishx** [comment]
> Thanks for reporting and helping out @masterwishx ! Really appreciate it :)

Glad to help, also founded after all in console of container that font/api folder not found

**Comment by gregtux77** [comment]
> Did you also changed pi.Alert URL from default to you URL?

i change

> jokobsk/pi.alert_dev:sha-b5f0a64

Hello ,

It's perfect . I deployed the dev version and I no longer have any errors. The home/pi/pialert/front/api directory exists.

I reactivated the API and Apprise.. I'll test a little more but I think it's ok

Congratulations guys and thanks again for the responsiveness

**Comment by haferm** [comment]
Hi, i have installed jokobsk/pi.alert_dev:sha-b5f0a64 however i have the strong feeling mail send in general is still not working, i see nothing in gerads to mail in any logs (where to look??) Also from docker logs pialert -f i see no events for test mail... However i was able to crate following screenshot not sure if this is an issue?.. 

![image](https://user-images.githubusercontent.com/22625877/217807431-8c7d5d9f-6bdb-448e-b515-fa4166bf8e6a.png)

**Comment by jokob-sk** [comment]
🆕 New release is live -> closing this issue:

- Release announcement: https://github.com/jokob-sk/Pi.Alert/releases/tag/v23.03.11
- Docker image: https://registry.hub.docker.com/r/jokobsk/pi.alert
